import type { ThemeTypes } from "@/types/themeTypes/ThemeType";

const BLUE_THEME: ThemeTypes = {
  name: "BLUE_THEME",
  dark: false,
  variables: {
    "border-color": "#e5eaef",
    "border-opacity": 1,
  },
  colors: {
    primary: "#5D87FF",
    secondary: "#49BEFF",
    info: "#539BFF",
    success: "#13DEB9",
    accent: "#FFAB91",
    warning: "#FFAE1F",
    error: "#FA896B",
    lightprimary: "#ECF2FF",
    lightsecondary: "#E8F7FF",
    lightsuccess: "#E6FFFA",
    lighterror: "#FDEDE8",
    lightinfo: "#EBF3FE",
    lightwarning: "#FEF5E5",
    textPrimary: "#2A3547",
    textSecondary: "#2A3547",
    borderColor: "#e5eaef",
    inputBorder: "#DFE5EF",
    containerBg: "#ffffff",
    background: "#ffffff",
    hoverColor: "#f6f9fc",
    surface: "#fff",
    "on-surface-variant": "#fff",
    grey100: "#F2F6FA",
    grey200: "#EAEFF4",
  },
};

const AQUA_THEME: ThemeTypes = {
  name: "AQUA_THEME",
  dark: false,
  variables: {
    "border-color": "#e5eaef",
    "border-opacity": 1,
  },
  colors: {
    primary: "#0074BA",
    secondary: "#47D7BC",
    info: "#539BFF",
    success: "#13DEB9",
    accent: "#FFAB91",
    warning: "#FFAE1F",
    error: "#FA896B",
    lightprimary: "#EFF9FF",
    lightsecondary: "#EDFBF7",
    lightsuccess: "#E6FFFA",
    lighterror: "#FDEDE8",
    lightinfo: "#EBF3FE",
    lightwarning: "#FEF5E5",
    textPrimary: "#2A3547",
    textSecondary: "#2A3547",
    borderColor: "#e5eaef",
    inputBorder: "#DFE5EF",
    containerBg: "#ffffff",
    background: "#ffffff",
    hoverColor: "#f6f9fc",
    surface: "#fff",
    "on-surface-variant": "#fff",
    grey100: "#F2F6FA",
    grey200: "#EAEFF4",
  },
};

const PURPLE_THEME: ThemeTypes = {
  name: "PURPLE_THEME",
  dark: false,
  variables: {
    "border-color": "#e5eaef",
    "border-opacity": 1,
  },
  colors: {
    primary: "#763EBD",
    secondary: "#95CFD5",
    info: "#539BFF",
    success: "#13DEB9",
    accent: "#FFAB91",
    warning: "#FFAE1F",
    error: "#FA896B",
    lightprimary: "#F2ECF9",
    lightsecondary: "#EDF8FA",
    lightsuccess: "#E6FFFA",
    lighterror: "#FDEDE8",
    lightinfo: "#EBF3FE",
    lightwarning: "#FEF5E5",
    textPrimary: "#2A3547",
    textSecondary: "#2A3547",
    borderColor: "#e5eaef",
    inputBorder: "#DFE5EF",
    containerBg: "#ffffff",
    background: "#ffffff",
    hoverColor: "#f6f9fc",
    surface: "#fff",
    "on-surface-variant": "#fff",
    grey100: "#F2F6FA",
    grey200: "#EAEFF4",
  },
};

const GREEN_THEME_OLD: ThemeTypes = {
  name: "GREEN_THEME",
  dark: false,
  variables: {
    "border-color": "#e5eaef",
    "border-opacity": 1,
  },
  colors: {
    primary: "#0A7EA4",
    secondary: "#CCDA4E",
    info: "#539BFF",
    success: "#13DEB9",
    accent: "#FFAB91",
    warning: "#FFAE1F",
    error: "#FA896B",
    lightprimary: "#F4F9FB",
    lightsecondary: "#FAFBEF",
    lightsuccess: "#E6FFFA",
    lighterror: "#FDEDE8",
    lightinfo: "#EBF3FE",
    lightwarning: "#FEF5E5",
    textPrimary: "#2A3547",
    textSecondary: "#2A3547",
    borderColor: "#e5eaef",
    inputBorder: "#DFE5EF",
    containerBg: "#ffffff",
    background: "#ffffff",
    hoverColor: "#f6f9fc",
    surface: "#fff",
    "on-surface-variant": "#fff",
    grey100: "#F2F6FA",
    grey200: "#EAEFF4",
  },
};

const GREEN_THEME: ThemeTypes = {
  name: "GREEN_THEME",
  dark: false,
  variables: {
    "border-color": "#e5e7eb",
    "border-opacity": 1,
  },
  colors: {
    primary: "#66BB6A",
    secondary: "#81C784",
    info: "#0EA5E9",
    success: "#22C55E",
    warning: "#F59E0B",
    error: "#EF4444",
    accent: "#A5D6A7",

    lightprimary: "#E8F5E9",
    lightsecondary: "#F1F8E9",
    lightsuccess: "#DCFCE7",
    lighterror: "#FEE2E2",
    lightinfo: "#E0F2FE",
    lightwarning: "#FEF3C7",

    textPrimary: "#111827",
    textSecondary: "#374151",
    borderColor: "#E5E7EB",
    inputBorder: "#D1D5DB",
    containerBg: "#FFFFFF",
    background: "#FFFFFF",
    hoverColor: "#F9FAFB",
    surface: "#FFFFFF",
    "on-surface-variant": "#F3F4F6",

    grey100: "#F3F4F6",
    grey200: "#E5E7EB",
  },
};

const CYAN_THEME: ThemeTypes = {
  name: "CYAN_THEME",
  dark: false,
  variables: {
    "border-color": "#e5eaef",
    "border-opacity": 1,
  },
  colors: {
    primary: "#01C0C8",
    secondary: "#FB9678",
    info: "#539BFF",
    success: "#00e676",
    accent: "#FFAB91",
    warning: "#FFAE1F",
    error: "#FA896B",
    lightprimary: "#EBF9FA",
    lightsecondary: "#FFF5F2",
    lightsuccess: "#E6FFFA",
    lighterror: "#FDEDE8",
    lightinfo: "#EBF3FE",
    lightwarning: "#FEF5E5",
    textPrimary: "#2A3547",
    textSecondary: "#2A3547",
    borderColor: "#e5eaef",
    inputBorder: "#DFE5EF",
    containerBg: "#ffffff",
    background: "#ffffff",
    hoverColor: "#f6f9fc",
    surface: "#fff",
    "on-surface-variant": "#fff",
    grey100: "#F2F6FA",
    grey200: "#EAEFF4",
  },
};

const ORANGE_THEME: ThemeTypes = {
  name: "ORANGE_THEME",
  dark: false,
  variables: {
    "border-color": "#e5eaef",
    "border-opacity": 1,
  },
  colors: {
    primary: "#FA896B",
    secondary: "#0074BA",
    info: "#539BFF",
    success: "#00e676",
    accent: "#FFAB91",
    warning: "#ffe57f",
    error: "#FA896B",
    lightprimary: "#FBF2EF",
    lightsecondary: "#EFF9FF",
    lightsuccess: "#E6FFFA",
    lighterror: "#FDEDE8",
    lightinfo: "#EBF3FE",
    lightwarning: "#FEF5E5",
    textPrimary: "#2A3547",
    textSecondary: "#2A3547",
    borderColor: "#e5eaef",
    inputBorder: "#DFE5EF",
    containerBg: "#ffffff",
    background: "#ffffff",
    hoverColor: "#f6f9fc",
    surface: "#fff",
    "on-surface-variant": "#fff",
    grey100: "#F2F6FA",
    grey200: "#EAEFF4",
  },
};

const RED_THEME: ThemeTypes = {
  name: "RED_THEME",
  dark: false,
  variables: {
    "border-color": "#e5eaef",
    "border-opacity": 1,
  },
  colors: {
    primary: "#E53935",
    secondary: "#FF7043",
    info: "#539BFF",
    success: "#13DEB9",
    accent: "#FFAB91",
    warning: "#FFAE1F",
    error: "#E53935",
    lightprimary: "#FDECEA",
    lightsecondary: "#FFF3F0",
    lightsuccess: "#E6FFFA",
    lighterror: "#FDEDE8",
    lightinfo: "#EBF3FE",
    lightwarning: "#FEF5E5",
    textPrimary: "#2A3547",
    textSecondary: "#2A3547",
    borderColor: "#e5eaef",
    inputBorder: "#DFE5EF",
    containerBg: "#ffffff",
    background: "#ffffff",
    hoverColor: "#f6f9fc",
    surface: "#fff",
    "on-surface-variant": "#fff",
    grey100: "#F2F6FA",
    grey200: "#EAEFF4",
  },
};

export {
  BLUE_THEME,
  AQUA_THEME,
  ORANGE_THEME,
  PURPLE_THEME,
  GREEN_THEME_OLD,
  GREEN_THEME,
  CYAN_THEME,
  RED_THEME,
};
